services:
  db:
    image: postgres:14-alpine
    container_name: UTFlix-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: minhaapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d minhaapi -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  cliente-service:
    build: ./cliente-service
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Schema 'cliente'
      DATABASE_URL: "postgresql://admin:admin@db:5432/minhaapi?schema=cliente"
    # Este comando está correto
    command: sh -c "npx prisma migrate dev && npm run dev"

  filmes-service:
    build: ./filmes-service
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Schema 'filmes'
      DATABASE_URL: "postgresql://admin:admin@db:5432/minhaapi?schema=filmes"
    # Este comando agora vai funcionar
    command: sh -c "sleep 10 && npx prisma migrate dev && npm run dev"

volumes:
  pgdata: