version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: UTFlix-postgres
    restart: always
    ports:
      - "5432:5432" # Expõe a porta do Postgres para o seu computador
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: minhaapi
    volumes:
      - ./pgdata:/var/lib/postgresql/data # Garante que os dados do banco não se percam

  # Serviço da Aplicação Node.js
  app:
    build: . # Constrói a imagem a partir do Dockerfile na pasta atual
    container_name: UTFlix-app
    ports:
      - "3000:3000" # Expõe a porta da API
    volumes:
      - ./src:/usr/app/src # Mapeia seu código local para dentro do contêiner
    depends_on:
      - db # Garante que o banco de dados inicie antes da aplicação
    environment:
      DATABASE_URL: "postgresql://admin:admin@db:5432/minhaapi?schema=public" 