services:
  db:
    image: postgres:14-alpine
    container_name: UTFlix-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: minhaapi
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: UTFlix-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://admin:admin@db:5432/minhaapi?schema=public"
    command: >
      sh -c "npx prisma migrate deploy && npm run dev"
