openapi: 3.0.3
info:
  title: UTFlix - Serviço de Filmes
  version: 1.0.0
servers:
  - url: http://localhost:3001
paths:
  /filmes:
    get:
      responses:
        '200':
          description: Lista de filmes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Filme'
  /filmes/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: Filme
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Filme' }
        '404': { description: Não encontrado }
components:
  schemas:
    Filme:
      type: object
      properties:
        idFilme: { type: integer }
        titulo: { type: string }
        anoLancamento: { type: integer }
        rating: { type: number }
        duration: { type: string }
        createdAt: { type: string, format: date-time }