# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: JavaScript Linter (ESLint)

# Gatilhos: quando este workflow deve rodar
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # ID do job, usado na regra de proteção de branch
  lint-backend:
    # Nome de exibição do job
    name: lint-backend
    
    # O workflow rodará em uma máquina virtual Linux (Ubuntu)
    runs-on: ubuntu-latest

    # Define o diretório de trabalho padrão para todos os comandos 'run'
    defaults:
      run:
        working-directory: ./backend

    steps:
    # 1. Clona o seu repositório para dentro da máquina virtual
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Configura a versão do Node.js (sem cache)
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    # 3. Instala as dependências a partir do lockfile
    - name: Install dependencies
      run: npm install

    # 4. Roda o ESLint para validar o código
    - name: Run ESLint
      run: npm run lint
