# .github/workflows/linter.yml

name: JavaScript Linter (ESLint)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # O nome deste job é 'lint'. Usaremos ele na regra de proteção.
  lint:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x' # Pode ajustar a versão se necessário
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint
