name: JavaScript Linter (ESLint)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-backend:
    name: lint-backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BackEnd # Isto está correto, é a raiz do seu workspace

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        # Esta linha está correta, aponta para o package-lock do workspace
        cache-dependency-path: BackEnd/package-lock.json

    - name: Install dependencies
      # 'npm install' na raiz do workspace instala tudo (correto)
      run: npm install

    - name: Run ESLint
      # --- ESTA É A MUDANÇA ---
      # Trocamos 'npx eslint .' pelo script 'npm run lint'
      # que roda o lint em todos os sub-projetos (--workspaces)
      run: npm run lint
