name: JavaScript Linter (ESLint)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-backend:
    name: lint-backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BackEnd

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        # ESTA LINHA ABAIXO RESOLVE O ERRO:
        cache-dependency-path: BackEnd/package-lock.json

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npx eslint .
